project:
  type: website
  output-dir: docs

website:
  title: "AMSA - Fall 2025"
  description: "Course materials for AMSA - Fall 2025"
  site-url: "https://francescsolsonatehas.github.io/AMSA-AWS/index.html"
  repo-url: https://github.com/francescsolsonatehas/AMSA-AWS

  sidebar:
    logo: /figs/logo.png
    logo-width: 75px
    logo-height: 75px
    logo-alt: "AMSA Logo"
    pinned: true
    tools:
    - icon: house
      href: "index.html"
      text: "Home"
    - icon: github
      href: "https://github.com/francescsolsonatehas/AMSA-AWS"
      text: "GitHub organization"
    - icon: person-fill
      text: "Sakai"
      href: "https://cv.udl.cat/"

    style: "docked"
    search: false
    collapse-level: 1
    contents:
      - section: Laboratories
        contents:
          - href: ./laboratories/01-foundations/01-aws-introduction.qmd
            text: Laboratori 01 路 Introducci贸 a AWS
          - href: ./laboratories/01-foundations/02-aws-wordpress.qmd
            text: Laboratori 02 路 Desplegament d'una aplicaci贸 web amb AWS
  
format:
  html:
    toc: true
    theme: 
      - cosmo
      - brand
