project:
  type: website
  output-dir: docs

website:
  title: "AMSA - Fall 2025"
  description: "Course materials for AMSA - Fall 2025"
  site-url: "https://amsa-gei-udl-2526-105013.github.io/course/"
  repo-url: https://github.com/amsa-gei-udl-2526-105013/course/

  sidebar:
    logo: /figs/logo.png
    logo-width: 75px
    logo-height: 75px
    logo-alt: "AMSA Logo"
    pinned: true
    tools:
    - icon: house
      href: "index.html"
      text: "Home"
    - icon: github
      href: "https://github.com/amsa-gei-udl-2526-105013/course/"
      text: "GitHub organization"
    - icon: person-fill
      text: "Sakai"
      href: "https://cv.udl.cat/"

    style: "docked"
    search: false
    collapse-level: 1
    contents:
      - section: Informaci贸 del curs
        contents:
          - href: ./course-information/schedule.html
            text: Planificaci贸
      - section: Diapositives
        contents:
          - href: ./slides/01-foundations-of-systems-administration.qmd
            text: Unitat 01 路 Fonaments de l'Administraci贸 de Sistemes
      - section: Lecture materials
      - section: Laboratories
      - section: Projects
      - section: Activities
  
format:
  html:
    toc: true
    theme: 
      - cosmo
      - brand
